### ISSUE TITLE
1D inputs?

### ISSUE THREAD

**Issue by dominikstrb** [kbonnen/BonnenEtAl2015_KalmanFilterCode#1]
Hi!

I really appreciate you putting the code for the Kalman filter fitting online. Trying to reproduce the results, I have trouble understanding one thing:

The inputs to your function are 1-dimensional time series per trial. Are you using only the x or y values? Or are you averaging them before fitting?

Best,
Dominik

**Comment by kbonnen** [comment]
The Kalman code I've posted here only fits a single dimension at a time.  I believe the example data and figure are from the horizontal direction of the 2D tracking experiment.  

If you were interested in capturing 2D tracking behavior with this code, I would recommend fitting each dimension separately.  Then you could average the fitted values.  I wouldn't do any averaging before fitting.

Alternatively (and particularly if you think there is an interaction between the two dimensions) you could develop a Kalman filter model that actually acts on a two dimensional input.  

Thanks,
Kate

**Comment by dominikstrb** [comment]
Hi Kate,

thanks for your answer! Since your model treats the two dimensions independently, it is okay to fit the "perceptual uncertainties" separately. That makes sense.

I am currently working with a group of students, trying to replicate the findings from your paper and thinking about possible extensions of the experimental paradigm. If you're interested, I will keep you in the loop if we get any interesting results.

Thanks,
Dominik
